/* PLEASE NOTE WE CANNOT JUST COPY AND PASTE THIS IN IT NEEDS TO GO THROUGH THIS PROCESS:
1. Configure .ioc as described (TIM3 PSC=1279 ARR=999, TIM2 PSC=63999 ARR=999, ADC IN11, PA8 as GPIO Output)
2. Press generate code — CubeIDE writes all the init functions
3. Then only add your code inside the /* USER CODE BEGIN */ /* blocks shown below 
4. The four sections you need to fill in are PV, BEGIN 2, BEGIN 3, and BEGIN 4 */

/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  */
/* USER CODE END Header */

#include "main.h"

/* USER CODE BEGIN PV */
volatile uint32_t adcValue = 0;
#define SERVO_MIN  49    // 1ms pulse = 0 degrees
#define SERVO_MAX  99    // 2ms pulse = 180 degrees
/* USER CODE END PV */

/* These are auto-generated by CubeIDE - do not touch */
ADC_HandleTypeDef hadc1;
TIM_HandleTypeDef htim2;
TIM_HandleTypeDef htim3;

/* Function prototypes - auto-generated */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_TIM2_Init(void);
static void MX_TIM3_Init(void);

int main(void)
{
    /* Auto-generated HAL init - do not touch */
    HAL_Init();
    SystemClock_Config();

    /* Auto-generated peripheral inits - do not touch */
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();

    /* USER CODE BEGIN 2 */
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);  // Start PWM on PA6 for servo
    HAL_TIM_Base_Start_IT(&htim2);              // Start TIM2 for LED blink at 1Hz
    /* USER CODE END 2 */

    while (1)
    {
        /* USER CODE BEGIN 3 */
        HAL_ADC_Start_IT(&hadc1);   // Keep reading potentiometer
        HAL_Delay(10);              // Small delay to avoid flooding ADC
        /* USER CODE END 3 */
    }
}

/* USER CODE BEGIN 4 */

// Fires when ADC conversion is complete
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        adcValue = HAL_ADC_GetValue(&hadc1);  // Read potentiometer (0-4095)

        // Map potentiometer (0-4095) to servo range (49-99)
        uint32_t servoPos = SERVO_MIN + (adcValue * (SERVO_MAX - SERVO_MIN)) / 4095;
        __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, servoPos);
    }
}

// Fires every 500ms from TIM2 to toggle LED on PA8
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM2)
    {
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_8);  // Toggle PA8 (LED1)
    }
}

/* USER CODE END 4 */

/* Auto-generated clock config - do not touch anything below this */
void SystemClock_Config(void) { /* generated by CubeIDE */ }
static void MX_GPIO_Init(void) { /* generated by CubeIDE */ }
static void MX_ADC1_Init(void) { /* generated by CubeIDE */ }
static void MX_TIM2_Init(void) { /* generated by CubeIDE */ }
static void MX_TIM3_Init(void) { /* generated by CubeIDE */ }
