#include "stm32f4xx_hal.h"
#include <stdio.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* USER SETTINGS                                                       */
/* ------------------------------------------------------------------ */
#define STUDENT_ID      "25895273" 

/* ------------------------------------------------------------------ */
/* LCD / PCF8574 DEFINES                                               */
/* ------------------------------------------------------------------ */
#define LCD_I2C_ADDR    (0x27 << 1)   /* A0,A1,A2 all pulled high   */
#define LCD_RS          (1 << 0)
#define LCD_RW          (1 << 1)
#define LCD_EN          (1 << 2)
#define LCD_BT          (1 << 3)      /* Backlight always on         */

/* HD44780 commands */
#define LCD_CLEAR       0x01
#define LCD_HOME        0x02
#define LCD_ENTRY_MODE  0x06
#define LCD_DISPLAY_ON  0x0C
#define LCD_FUNC_SET    0x28          /* 4-bit, 2 lines, 5x8 font   */
#define LCD_SET_DDRAM   0x80

/* Row DDRAM offsets */
#define ROW0  0x00
#define ROW1  0x40

/* LED */
#define LED_PIN         GPIO_PIN_5
#define LED_PORT        GPIOA
#define LED_BLINK_MS    500           /* 500ms on + 500ms off = 1Hz  */

/* PRIVATE STATE                                                       */
static I2C_HandleTypeDef  *_hi2c;
static ADC_HandleTypeDef  *_hadc;
static TIM_HandleTypeDef  *_htim;

static uint32_t last_blink = 0;
static uint8_t  led_state  = 0;
static char     line1[17];

/* LCD DRIVER                                                          */
static void lcd_i2c_write(uint8_t byte)
{
    HAL_I2C_Master_Transmit(_hi2c, LCD_I2C_ADDR, &byte, 1, HAL_MAX_DELAY);
}

static void lcd_enable_pulse(uint8_t byte)
{
    lcd_i2c_write(byte |  LCD_EN);
    HAL_Delay(1);
    lcd_i2c_write(byte & ~LCD_EN);
    HAL_Delay(1);
}

static void lcd_write_nibble(uint8_t nibble_byte, uint8_t ctrl)
{
    uint8_t byte = (nibble_byte & 0xF0) | LCD_BT | ctrl;
    lcd_enable_pulse(byte);
}

/* Send a command byte (RS=0) */
static void LCD_SendCmd(uint8_t cmd)
{
    lcd_write_nibble(cmd & 0xF0,        0x00);   /* upper nibble */
    lcd_write_nibble((cmd << 4) & 0xF0, 0x00);   /* lower nibble */
    if (cmd == LCD_CLEAR || cmd == LCD_HOME)
        HAL_Delay(2);
}

/* Send a data byte (RS=1) */
static void LCD_SendData(uint8_t data)
{
    lcd_write_nibble(data & 0xF0,        LCD_RS);
    lcd_write_nibble((data << 4) & 0xF0, LCD_RS);
}

/* Write a null-terminated string */
static void LCD_SendString(const char *str)
{
    while (*str) LCD_SendData((uint8_t)(*str++));
}

/* Set cursor position */
static void LCD_SetCursor(uint8_t col, uint8_t row)
{
    uint8_t offsets[] = {ROW0, ROW1};
    LCD_SendCmd(LCD_SET_DDRAM | (col + offsets[row & 0x01]));
}

/* Initialise the LCD in 4-bit mode */
static void LCD_Init(void)
{
    HAL_Delay(50);

    /* HD44780 reset sequence */
    lcd_write_nibble(0x30, 0x00); HAL_Delay(5);
    lcd_write_nibble(0x30, 0x00); HAL_Delay(1);
    lcd_write_nibble(0x30, 0x00); HAL_Delay(1);
    lcd_write_nibble(0x20, 0x00); HAL_Delay(1);   /* switch to 4-bit */

    LCD_SendCmd(LCD_FUNC_SET);
    LCD_SendCmd(LCD_DISPLAY_ON);
    LCD_SendCmd(LCD_CLEAR);
    LCD_SendCmd(LCD_ENTRY_MODE);
}

/* PUBLIC API — call these from main.c                                */

/*
 * Lab_Init()
 * Pass in pointers to the HAL handles generated by CubeIDE.
 * Call once in USER CODE BEGIN 2, after all MX_xxx_Init() calls.
 *
 * Example:
 *   Lab_Init(&hi2c1, &hadc1, &htim2);
 */
void Lab_Init(I2C_HandleTypeDef *hi2c,
              ADC_HandleTypeDef *hadc,
              TIM_HandleTypeDef *htim)
{
    _hi2c = hi2c;
    _hadc = hadc;
    _htim = htim;

    /* Activity 5: starting the timer */
    HAL_TIM_Base_Start(_htim);

    /* Activity 3: initialise LCD and show student ID */
    LCD_Init();

    LCD_SetCursor(0, 0);
    LCD_SendString("SID : ");
    LCD_SendString(STUDENT_ID);

    LCD_SetCursor(0, 1);
    LCD_SendString("MECHATRONICS 1");

    HAL_Delay(1000);
}

/*
 * Lab_Run()
 * Call on every iteration of while(1).
 * Reads ADC, updates LCD (Activity 4), and blinks LED at 1 Hz (Activity 5).
 *
 * Example:
 *   while (1) {
 *       Lab_Run();
 *   }
 */
void Lab_Run(void)
{
    /*Activity 4: read ADC and update LCD*/
    HAL_ADC_Start(_hadc);
    uint32_t adc_value = 0;
    if (HAL_ADC_PollForConversion(_hadc, 100) == HAL_OK)
        adc_value = HAL_ADC_GetValue(_hadc);
    HAL_ADC_Stop(_hadc);

    snprintf(line1, sizeof(line1), "ADC : %-4lu      ", (unsigned long)adc_value);
    line1[16] = '\0';

    LCD_SetCursor(0, 0);
    LCD_SendString(line1);

    LCD_SetCursor(0, 1);
    LCD_SendString("MECHATRONICS 1  ");

    /*Activity 5: non-blocking 1 Hz LED blink */
    uint32_t now_ms = __HAL_TIM_GET_COUNTER(_htim) / 1000;
    if ((now_ms - last_blink) >= LED_BLINK_MS)
    {
        last_blink = now_ms;
        led_state  = !led_state;
        HAL_GPIO_WritePin(LED_PORT, LED_PIN,
                          led_state ? GPIO_PIN_SET : GPIO_PIN_RESET);
    }

    HAL_Delay(100);   /* ~10 LCD refreshes per second */
}
